server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:4306/playmate
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibrnate.orm.jdbc.bind: trace
